import type { Product } from "./types";
import boyShirt from "@/assets/p-boy-shirt.jpg";
import boyPanjabi from "@/assets/p-boy-panjabi.jpg";
import boyDungaree from "@/assets/p-boy-dungaree.jpg";
import girlFrock from "@/assets/p-girl-frock.jpg";
import girlThreePiece from "@/assets/p-girl-three-piece.jpg";
import babySet from "@/assets/p-baby-set.jpg";
import newbornSet from "@/assets/p-newborn-set.jpg";

const KID_SIZES = ["১-২ বছর", "৩-৪ বছর", "৫-৬ বছর", "৭-৮ বছর"];

export const PRODUCTS: Product[] = [
  {
    id: "rf-101",
    name: "ছেলেদের কটন ক্যাজুয়াল শার্ট",
    category: "boys",
    price: 690,
    oldPrice: 950,
    image: boyShirt,
    description:
      "১০০% কটন কাপড়ে তৈরি আরামদায়ক ক্যাজুয়াল শার্ট। গরমে বাচ্চার ত্বকের জন্য নরম ও শ্বাস-প্রশ্বাসযোগ্য।",
    sizes: KID_SIZES,
    colors: ["আকাশি", "সাদা", "নেভি"],
    stock: 24,
    rating: 4.7,
    featured: true,
  },
  {
    id: "rf-102",
    name: "ছেলেদের সেমি-লং পাঞ্জাবি",
    category: "boys",
    price: 1150,
    oldPrice: 1450,
    image: boyPanjabi,
    description:
      "উৎসবের জন্য এমব্রয়ডারি করা প্রিমিয়াম পাঞ্জাবি। ঈদ ও যেকোনো অনুষ্ঠানে বাচ্চার জন্য পারফেক্ট।",
    sizes: KID_SIZES,
    colors: ["অফ হোয়াইট", "ক্রিম"],
    stock: 12,
    rating: 4.9,
    featured: true,
  },
  {
    id: "rf-103",
    name: "কিডস ডেনিম ডাঙ্গারি",
    category: "boys",
    price: 990,
    image: boyDungaree,
    description: "স্ট্রেচেবল ডেনিমের আরামদায়ক ডাঙ্গারি, দৈনন্দিন খেলাধুলার জন্য উপযুক্ত।",
    sizes: KID_SIZES,
    colors: ["ব্লু ডেনিম"],
    stock: 8,
    rating: 4.5,
  },
  {
    id: "rf-201",
    name: "মেয়েদের পার্টি ফ্রক",
    category: "girls",
    price: 1290,
    oldPrice: 1690,
    image: girlFrock,
    description: "নরম টুলে তৈরি গোলাপি পার্টি ফ্রক। জন্মদিন কিংবা যেকোনো উৎসবে রাজকন্যার সাজ।",
    sizes: KID_SIZES,
    colors: ["পিংক", "পিচ"],
    stock: 18,
    rating: 4.8,
    featured: true,
  },
  {
    id: "rf-202",
    name: "মেয়েদের থ্রি-পিস সেট",
    category: "girls",
    price: 1490,
    oldPrice: 1850,
    image: girlThreePiece,
    description: "এমব্রয়ডারি করা ল্যাভেন্ডার থ্রি-পিস সেট, সাথে ওড়না ও হেয়ারব্যান্ড ফ্রি।",
    sizes: KID_SIZES,
    colors: ["ল্যাভেন্ডার"],
    stock: 10,
    rating: 4.6,
    featured: true,
  },
  {
    id: "rf-301",
    name: "বেবি সফট কটন টু-পিস সেট",
    category: "baby",
    price: 560,
    oldPrice: 720,
    image: babySet,
    description: "অতি নরম কটনের টু-পিস সেট, বেবির সংবেদনশীল ত্বকের জন্য নিরাপদ।",
    sizes: ["৬-৯ মাস", "৯-১২ মাস", "১-২ বছর"],
    colors: ["ল্যাভেন্ডার", "পিংক"],
    stock: 30,
    rating: 4.7,
    featured: true,
  },
  {
    id: "rf-401",
    name: "নিউ বর্ন গিফট সেট",
    category: "newborn",
    price: 890,
    oldPrice: 1100,
    image: newbornSet,
    description: "নবজাতকের জন্য সম্পূর্ণ গিফট সেট — বডিস্যুট, ক্যাপ ও মিটেন সহ।",
    sizes: ["০-৩ মাস", "৩-৬ মাস"],
    colors: ["সাদা", "পিংক"],
    stock: 15,
    rating: 5,
    featured: true,
  },
  {
    id: "rf-402",
    name: "নিউ বর্ন কটন নিমা সেট",
    category: "newborn",
    price: 450,
    image: newbornSet,
    description: "হালকা কটনের নিমা সেট, সারাদিন আরামে রাখবে আপনার নবজাতককে।",
    sizes: ["০-৩ মাস", "৩-৬ মাস"],
    colors: ["সাদা"],
    stock: 40,
    rating: 4.4,
  },
];
